### ISSUE TITLE
Teacher able to see student participation data analytic

### ISSUE THREAD

**Issue by VictorChenLi** [VictorChenLi/BatonMeteor#82]
First step for Data Analytics #23, Teacher able to see student's history participation data

- [x] #134  The percentage different from last week (short line chart and number in list view) and a list of all the class records

- [x] #135  To show the trend of each class (Line chart), participation type breakdown and students list who participated

- [x] #133  On student in class participation record page, show student's overall participation rate (above or lower average) in specific classroom and trends.

4. more to discussion ...
